---
name: Renovate

"on":
  schedule:
    - cron: "47 9 * * 5"
  workflow_dispatch:

enable-email-notifications: true

concurrency:
  group: renovate-${{ forgejo.repository }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: oci-deps
    timeout-minutes: 60
    container:
      image: docker.io/renovate/renovate:latest@sha256:2c7b118cb2d1b7137e63322efc0e1d3d96d5f6937ec1c35c3cd9b7de73a8ed29
      volumes:
        - /opt/cache/renovate:/tmp/renovate/cache
    env:
      LOG_LEVEL: info
      RENOVATE_CACHE_DIR: /tmp/renovate/cache
      RENOVATE_ENDPOINT: https://git.tacomafia.net/api/v1
      RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
      RENOVATE_HOST_RULES: '[{"hostType":"forgejo","matchHost":"https://git.tacomafia.net/","allowInternal":true}]'
      RENOVATE_INTERNAL_HOST_ACCESS: block
      RENOVATE_ONBOARDING: "false"
      RENOVATE_PLATFORM: forgejo
      RENOVATE_REPOSITORY_CACHE: enabled
      RENOVATE_REPOSITORIES: kylhill/nixos
      RENOVATE_REQUIRE_CONFIG: required
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    steps:
      - name: Update dependencies
        run: renovate
