---
name: Renovate

"on":
  schedule:
    - cron: "47 9 * * 5"
  workflow_dispatch:

enable-email-notifications: true

concurrency:
  group: renovate-${{ forgejo.repository }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: oci-deps
    timeout-minutes: 60
    container:
      image: docker.io/renovate/renovate:latest@sha256:9a380ee32a5d3e299b1c24bf8c1c42f7d412fec4eec353a30de0527ba84ad30b
      volumes:
        - /opt/renovate-cache:/tmp/renovate/containerbase
    env:
      LOG_LEVEL: info
      RENOVATE_CONTAINERBASE_DIR: /tmp/renovate/containerbase
      RENOVATE_ENDPOINT: https://git.tacomafia.net/api/v1
      RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
      RENOVATE_HOST_RULES: '[{"hostType":"forgejo","matchHost":"https://git.tacomafia.net/","allowInternal":true}]'
      RENOVATE_INTERNAL_HOST_ACCESS: block
      RENOVATE_ONBOARDING: "false"
      RENOVATE_PLATFORM: forgejo
      RENOVATE_REPOSITORIES: kylhill/nixos
      RENOVATE_REQUIRE_CONFIG: required
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    steps:
      - name: Update dependencies
        run: renovate
